Fixed values for bleeds while bound and reduced cases tested
NightShadeI/Revolution-Rotation-Calculator- pull request #17
Opened 2017-11-12 23:28 UTC by NightShadeI

- Limited cases tested to bleeds, special bleeds or neither.
- Added multiplier in case you are walking target right when bind finishes and target is under bleed.
- Still requires overall testing.

2017-11-13 11:18 UTC, EZtouch commented on Revolution Rotation Calculator.py
> +Walking_Bleeds = {'FRAGMENTATION SHOT': 1, 'COMBUST': 1, 'SLAUGHER': 1.5}
This should be SLAUGHTER instead of SLAUGHER 🙂

2017-11-13 11:22 UTC, EZtouch requested changes
Fix typo

2017-11-13 22:49 UTC, NightShadeI commented
Alright going to start with testing here too soon.

2017-11-14 02:12 UTC, Wea1thRS commented
@NightShadeI Can you check out what I am planning on the other pull request? Could use your input on it. 😄

2017-11-14 09:51 UTC, merged